defaults:
  - model_checkpoint
  - early_stopping
  #  - model_summary
<<<<<<< HEAD
  - metrics_printer
#  - rich_progress_bar
=======
  - rich_progress_bar
<<<<<<< HEAD
<<<<<<< HEAD
  # - tensor_parity_plots
>>>>>>> f0b23a3 (Deriv and Si CSH datamodule)
=======
  - tensor_parity_plots
>>>>>>> 05386dc (Added magnetic deriv model and datamodule for Si and CSH dataset)
=======
  - parity_plots
  # - tensor_parity_plots
>>>>>>> 8fa5ce3 (Pre rebase save)
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: min
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/nmr_tensors_rmse"
  min_delta: 0.
  patience: 20
  check_on_train_epoch_end: True

#model_summary:
#  max_depth: -1
