# https://mlflow.org

mlflow:
  _target_: reax.loggers.mlflow.MLFlowLogger
  tracking_uri: "file:/home/mattia/Desktop/ml_codes/mlruns"
  experiment_name: diff_vs_direct_nmr_model
  run_name: direct_model - 100mol 
  tags:
    mlflow.user: ${oc.env:USER}
  prefix: ""
  artifact_location: null