# https://mlflow.org

mlflow:
  _target_: reax.loggers.mlflow.MLFlowLogger
  experiment_name: e3response_QM9-NMR
  run_name: try # diff_model - 500mol - no regularization on B_ind
  tags:
    mlflow.user: ${oc.env:USER}
  prefix: ""
  artifact_location: null
  # run_id: ""
